Algoritmo "semnome"
// Algoritmo para verificar se a pessoa é maior de idade
Var
// Seção de Declarações das variáveis 
idade:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

          escreva("sua idade: ")
          leia(idade)
          se  idade >= 18 entao
               escreva("Maior de Idade")
               senao
               escreva ("Menor de idade")
          fimse




Fimalgoritmo